### PR TITLE
Add 'circle' mode to secondary-camera output

### PR DESCRIPTION
**Pull request by Chabloz**
new feature: Add circle to secondary-camera output
Fix deprecated warning: use colorSpace instead of encoding

### CODE REVIEW

**Comment by Chabloz** [comment]
I needed a portal effect in my boilerplate. but as my gates were circular in shape, I needed the second camera to be able to use this geometry.
A demo of the effect in my boilerplate : https://onivers.com/teleport/

**Comment by diarmidmackenzie** [comment]
Thanks, I really appreciate the PR, and I think you have a valid use case, but not sure I want to solve it in this way.

My original code assumed a plane geometry (more precisely, it assumed a geometry with "height" and "width" properties), and uses this assumption to determine the aspect ratio for the output.  I can see you might want to output to other geometries (e.g. a circle) and I'd like to support that, but I don't really like extending the API with a list of different output geometries, which could go on & on (star?  triangle?  torus? cube? etc.)

My initial thought is that it would be preferable to adapt the schema as follows:

- output takes values "screen" or "scene" (with "plane" also preserved as an option for back-compatibility)
- new schema property: "aspectRatio", takes values "auto" (which only works if the output geometry has a "width" and "height" and operates as today), or a numerical value, in which case this is used for the aspect ratio: for your use case, you'd set this to 1.

I suspect this would meet your use case, and I think is more flexible going forwards than your suggested change.

What do you think?

An even simpler fix would be to just set aspect ratio to 1 in the case where the output geometry is missing either a "width" or "height" property.  That gives less flexibility, but would be a much simpler fix and would probably meet your needs?

**Comment by Chabloz** [comment]
Yes, modifying the schema for the ratio seems simple and flexible enough for the use case. I will try to adapt the PR.

**Comment by Chabloz** [comment]
Sry for the whitespace commit.

To summarize the changes:

`aspectRatio: {type: 'string', default: 'auto'}`

added to schema

```
if (this.data.aspectRatio !== 'auto' && isNaN(parseFloat(this.data.aspectRatio))) {
  console.error("aspectRatio must be a number or 'auto'");
}
this.aspectRatio = (this.data.aspectRatio === 'auto') ? 'auto' : parseFloat(this.data.aspectRatio);
```
Added to init

```
if (this.aspectRatio === 'auto') {
  this.camera.aspect = object.geometry.parameters.width / object.geometry.parameters.height;
} else {
  this.camera.aspect = this.aspectRatio;
}
```
Added to configureCamera

**Comment by diarmidmackenzie** [comment]
Sorry for delays here.  This is awesome, thank you so much.

**Pull request merged**
